# Naive Bayes using Balanced Dataset + Word ngrams

In [11]:
import numpy as np
import re
from sklearn.datasets import load_files
import pickle
import string
import pandas as pd
df = pd.read_csv('UseThisClean.csv')
X = df['clean_text']
y = df['Class']
df.head()

Class                                         clean_text
0      0  خيبة الأمل تشاؤما تقولا عزم لكفالة اليتيم بالع...
1      0           اسفا لجزره لماذا تنشر راهذا طرقه الاحرار
2      0           دار الحب لاتشتم اخوان امام العرب افهم اخ
3      0                                       السيد الملاح
4      0                     ابتسمة جزائرية بنكهة فلسطنية ه

In [12]:
import pandas as pd
from sklearn.feature_extraction.text import CountVectorizer

# Handle missing values in data
df['clean_text'] = df['clean_text'].fillna('')

# Convert the cleaned text to Unicode if necessary
df['clean_text'] = df['clean_text'].astype(str)

# Initialize CountVectorizer with word n-grams
ngram_range = (2, 2)  # Use 2-word  n-grams
vectorizer = CountVectorizer(max_features=9000, min_df=2, max_df=0.8, ngram_range=ngram_range)

# Fit and transform the cleaned text using CountVectorizer with word n-grams
X = vectorizer.fit_transform(df['clean_text'])


In [13]:
from sklearn.model_selection import train_test_split
from sklearn.naive_bayes import MultinomialNB

# Split the data into training and testing sets
X_train, X_test, y_train, y_test = train_test_split(X, df['Class'], test_size=0.2)

# Initialize the Naive Bayes classifier
classifier = MultinomialNB()

# Fit the classifier on the training data
classifier.fit(X_train, y_train)


MultinomialNB()

In [14]:
y_pred = classifier.predict(X_test)

In [15]:
from sklearn.metrics import classification_report, confusion_matrix, accuracy_score

print(confusion_matrix(y_test,y_pred))
print(classification_report(y_test,y_pred))
print(accuracy_score(y_test, y_pred))

[[593 171  21]
 [431 316  62]
 [304  73 373]]
              precision    recall  f1-score   support

           0       0.45      0.76      0.56       785
           1       0.56      0.39      0.46       809
           2       0.82      0.50      0.62       750

    accuracy                           0.55      2344
   macro avg       0.61      0.55      0.55      2344
weighted avg       0.61      0.55      0.55      2344

0.5469283276450512
