# SVM using Balanced Dataset + ngrams

In [1]:
import numpy as np
import re
from sklearn.datasets import load_files
import pickle
import string
import pandas as pd
df = pd.read_csv('UseThisClean.csv')
X = df['clean_text']
y = df['Class']
df.head()

Class                                         clean_text
0      0  خيبة الأمل تشاؤما تقولا عزم لكفالة اليتيم بالع...
1      0           اسفا لجزره لماذا تنشر راهذا طرقه الاحرار
2      0           دار الحب لاتشتم اخوان امام العرب افهم اخ
3      0                                       السيد الملاح
4      0                     ابتسمة جزائرية بنكهة فلسطنية ه

In [2]:
import pandas as pd
from sklearn.feature_extraction.text import CountVectorizer

# Handle missing values in data
df['clean_text'] = df['clean_text'].fillna('')

# Convert the cleaned text to Unicode if necessary
df['clean_text'] = df['clean_text'].astype(str)

# Initialize CountVectorizer with word n-grams
ngram_range = (4, 4)  # Use 4-word  n-grams
vectorizer = CountVectorizer(max_features=9000, min_df=2, max_df=0.8, ngram_range=ngram_range)

# Fit and transform the cleaned text using CountVectorizer with word n-grams
X = vectorizer.fit_transform(df['clean_text']).toarray()


In [3]:
from sklearn.model_selection import train_test_split
from sklearn.svm import SVC

# Split the data into training and testing sets
X_train, X_test, y_train, y_test = train_test_split(X, df['Class'], test_size=0.2, random_state=42)

from sklearn.svm import SVC

# Initialize the Support Vector Machine classifier

classifier = SVC(kernel='linear', random_state=0)

# Fit the classifier on the training data

classifier.fit(X_train, y_train)


SVC(kernel='linear', random_state=0)

In [4]:
y_pred = classifier.predict(X_test)

In [5]:
from sklearn.metrics import classification_report, confusion_matrix, accuracy_score

print(confusion_matrix(y_test,y_pred))
print(classification_report(y_test,y_pred))
print(accuracy_score(y_test, y_pred))

[[ 45 789   0]
 [ 10 764   0]
 [  3 714  19]]
              precision    recall  f1-score   support

           0       0.78      0.05      0.10       834
           1       0.34      0.99      0.50       774
           2       1.00      0.03      0.05       736

    accuracy                           0.35      2344
   macro avg       0.70      0.36      0.22      2344
weighted avg       0.70      0.35      0.22      2344

0.3532423208191126
