# Random Forest using Balanced Dataset + Word ngrams

In [1]:
import numpy as np
import re
from sklearn.datasets import load_files
import pickle
import string
import pandas as pd
df = pd.read_csv('UseThisClean.csv')
X = df['clean_text']
y = df['Class']
df.head()

Class                                         clean_text
0      0  خيبة الأمل تشاؤما تقولا عزم لكفالة اليتيم بالع...
1      0           اسفا لجزره لماذا تنشر راهذا طرقه الاحرار
2      0           دار الحب لاتشتم اخوان امام العرب افهم اخ
3      0                                       السيد الملاح
4      0                     ابتسمة جزائرية بنكهة فلسطنية ه

In [2]:
import pandas as pd
from sklearn.feature_extraction.text import CountVectorizer

# Handle missing values in data
df['clean_text'] = df['clean_text'].fillna('')

# Convert the cleaned text to Unicode if necessary
df['clean_text'] = df['clean_text'].astype(str)

# Initialize CountVectorizer with word n-grams
ngram_range = (3, 3)  # Use 1-word (unigram) n-grams
vectorizer = CountVectorizer(max_features=9000, min_df=2, max_df=0.95, ngram_range=ngram_range)

# Fit and transform the cleaned text using CountVectorizer with word n-grams
X = vectorizer.fit_transform(df['clean_text'])


In [3]:
from sklearn.model_selection import train_test_split
from sklearn.ensemble import RandomForestClassifier

# Split the data into training and testing sets
X_train, X_test, y_train, y_test = train_test_split(X, df['Class'], test_size=0.2, random_state=42)

from sklearn.ensemble import RandomForestClassifier

# Initialize the Naive Bayes classifier

classifier = RandomForestClassifier(n_estimators=100, random_state=42)


# Fit the classifier on the training data

classifier.fit(X_train, y_train) 

RandomForestClassifier(random_state=42)

In [4]:
y_pred = classifier.predict(X_test)

In [5]:
from sklearn.metrics import classification_report, confusion_matrix, accuracy_score

print(confusion_matrix(y_test,y_pred))
print(classification_report(y_test,y_pred))
print(accuracy_score(y_test, y_pred))

[[ 97 737   0]
 [ 32 735   7]
 [  2 659  75]]
              precision    recall  f1-score   support

           0       0.74      0.12      0.20       834
           1       0.34      0.95      0.51       774
           2       0.91      0.10      0.18       736

    accuracy                           0.39      2344
   macro avg       0.67      0.39      0.30      2344
weighted avg       0.66      0.39      0.30      2344

0.3869453924914676
